#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing...'

npx lint-staged --allow-empty ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄'
